export default {
  USER_ID: 'USER_ID',
  USER_NAME: 'USER_NAME',
  USER_EMAIL: 'USER_EMAIL',

  CUSTOM_CLIENT_ID: 'CUSTOM_CLIENT_ID',
  CUSTOM_CLIENT_SECRET: 'CUSTOM_CLIENT_SECRET',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
};
