export default {
  USER_ID: 'USER_ID',
  USER_NAME: 'USER_NAME',
  USER_EMAIL: 'USER_EMAIL',

  CREDENTIAL: 'CREDENTIAL',

  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',

  CLOCK: 'CLOCK',
};
