export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  IS_LOGGED_IN: 'IS_LOGGED_IN',

  GET_ALL_EMAILS: 'GET_ALL_EMAILS',
  OPEN_EMAIL: 'OPEN_EMAIL',
  MARK_AS_READ: 'MARK_AS_READ',
  DELETE_EMAIL: 'DELETE_EMAIL',

  PARSE_EMAIL: 'PARSE_EMAIL',
};
