export default {
  LOGIN: 'LOGIN',
  GET_ALL_EMAILS: 'GET_ALL_EMAILS',
  OPEN_EMAIL: 'OPEN_EMAIL',
  MARK_AS_READ: 'MARK_AS_READ',
  DELETE_EMAIL: 'DELETE_EMAIL',
  FORMAT_EMAIL: 'FORMAT_EMAIL',
};
